# Restaurant + Orders Dataset

In [1]:
import pandas as pd

In [2]:
men = pd.read_csv('menu_items.csv')
ords = pd.read_csv('order_details.csv')

# Menu Dataset

In [3]:
men.head(5)

   menu_item_id      item_name  category  price
0           101      Hamburger  American  12.95
1           102   Cheeseburger  American  13.95
2           103        Hot Dog  American   9.00
3           104  Veggie Burger  American  10.50
4           105   Mac & Cheese  American   7.00

In [4]:
ords.head(5)

   order_details_id  order_id order_date   order_time  item_id
0                 1         1     1/1/23  11:38:36 AM    109.0
1                 2         2     1/1/23  11:57:40 AM    108.0
2                 3         2     1/1/23  11:57:40 AM    124.0
3                 4         2     1/1/23  11:57:40 AM    117.0
4                 5         2     1/1/23  11:57:40 AM    129.0

In [5]:
# No. of rows and columns in Menu Dataset 
men.shape

(32, 4)

In [6]:
#name of columns in Menu 
men.columns

Index(['menu_item_id', 'item_name', 'category', 'price'], dtype='object')

In [7]:
men.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   menu_item_id  32 non-null     int64
 1   item_name     32 non-null     object
 2   category      32 non-null     object
 3   price         32 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ KB

In [8]:
men.describe()

       menu_item_id      price
count     32.000000  32.000000
mean     116.500000  13.285937
std        9.380832   3.858071
min      101.000000   5.000000
25%      108.750000  10.500000
50%      116.500000  13.950000
75%      124.250000  15.750000
max      132.000000  19.950000

In [9]:
# checking is there any null values 
men.isnull().sum()

menu_item_id    0
item_name       0
category        0
price           0
dtype: int64

In [10]:
men.dtypes

menu_item_id      int64
item_name        object
category         object
price           float64
dtype: object

# Orders Datasets

In [11]:
# No. of rows and columns in Orders Dataset 
ords.shape

(12234, 5)

In [12]:
#name of columns in Menu 
ords.columns

Index(['order_details_id', 'order_id', 'order_date', 'order_time', 'item_id'], dtype='object')

In [13]:
men.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   menu_item_id  32 non-null     int64
 1   item_name     32 non-null     object
 2   category      32 non-null     object
 3   price         32 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ KB

In [14]:
ords.describe()

       order_details_id      order_id       item_id
count      12234.000000  12234.000000  12097.000000
mean        6117.500000   2691.927415    115.202282
std         3531.795931   1546.026261      9.387580
min            1.000000      1.000000    101.000000
25%         3059.250000   1351.250000    107.000000
50%         6117.500000   2710.000000    114.000000
75%         9175.750000   4020.000000    123.000000
max        12234.000000   5370.000000    132.000000

In [15]:
# checking is there any null values 
ords.isnull().sum()

order_details_id      0
order_id              0
order_date            0
order_time            0
item_id             137
dtype: int64

In [16]:
# datatypes of all columns
ords.dtypes

order_details_id      int64
order_id              int64
order_date           object
order_time           object
item_id             float64
dtype: object

In [17]:
ords.item_id.isnull().sum()

np.int64(137)

In [18]:
# 137 null values are present in item_id column.

In [19]:
ords[ords.item_id.isnull()]

       order_details_id  order_id order_date   order_time  item_id
121                 122        50     1/1/23   6:41:01 PM      NaN
297                 298       125     1/2/23   8:31:06 PM      NaN
357                 358       147     1/3/23   2:32:51 PM      NaN
386                 387       161     1/3/23   4:43:46 PM      NaN
469                 470       200     1/3/23  10:24:05 PM      NaN
...                 ...       ...        ...          ...      ...
11716             11717      5149    3/28/23   2:48:50 PM      NaN
11903             11904      5225    3/29/23   5:40:52 PM      NaN
11906             11907      5226    3/29/23   5:43:56 PM      NaN
12021             12022      5281    3/30/23   4:56:04 PM      NaN
12063             12064      5303    3/30/23   9:15:27 PM      NaN

[137 rows x 5 columns]

In [20]:
# We will be going to replace the null values with 0 for better understanding.

In [21]:
ords.item_id.fillna(0)

0        109.0
1        108.0
2        124.0
3        117.0
4        129.0
         ...
12229    109.0
12230    129.0
12231    120.0
12232    122.0
12233    122.0
Name: item_id, Length: 12234, dtype: float64

In [22]:
ords.isnull().sum()

order_details_id      0
order_id              0
order_date            0
order_time            0
item_id             137
dtype: int64

In [23]:
# Now there is no null values present in an columns. Therefore our data is cleaned.

In [24]:
ords.columns

Index(['order_details_id', 'order_id', 'order_date', 'order_time', 'item_id'], dtype='object')

In [25]:
men.columns

Index(['menu_item_id', 'item_name', 'category', 'price'], dtype='object')

In [26]:
# Now the common column in both dataset is item_id but the name of the column in 'Menu Dataset' is different. Thats why 
# we will going to change the name of the column from 'menu_item_id' to only 'item_id' which is further used for join the both datasets.

In [27]:
men.rename(columns={'menu_item_id':'item_id'}, inplace=True)

In [28]:
men.columns

Index(['item_id', 'item_name', 'category', 'price'], dtype='object')

In [113]:
ords.isnull().sum()

order_details_id    0
order_id            0
order_date          0
order_time          0
item_id             0
hour                0
dtype: int64

In [112]:
ords.fillna(0, inplace=True)

In [114]:
# changing the dtype of item_id from float to int 
ords['item_id'] = ords['item_id'].astype('int')

In [30]:
pd.merge(ords, men, how='inner', on='item_id')

,order_details_id,order_id,order_date,order_time,item_id,item_name,category,price
0,1,1,1/1/23,11:38:36 AM,109.0,Korean Beef Bowl,Asian,17.95
1,2,2,1/1/23,11:57:40 AM,108.0,Tofu Pad Thai,Asian,14.50
2,3,2,1/1/23,11:57:40 AM,124.0,Spaghetti,Italian,14.50
3,4,2,1/1/23,11:57:40 AM,117.0,Chicken Burrito,Mexican,12.95
4,5,2,1/1/23,11:57:40 AM,129.0,Mushroom Ravioli,Italian,15.50
...,...,...,...,...,...,...,...,...
12092,12230,5369,3/31/23,10:05:04 PM,109.0,Korean Beef Bowl,Asian,17.95
12093,12231,5369,3/31/23,10:05:04 PM,129.0,Mushroom Ravioli,Italian,15.50
12094,12232,5369,3/31/23,10:05:04 PM,120.0,Steak Torta,Mexican,13.95
12095,12233,5369,3/31/23,10:05:04 PM,122.0,Chips & Salsa,Mexican,7.00
12096,12234,5370,3/31/23,10:15:48 PM,122.0,Chips & Salsa,Mexican,7.00

# Basic Questions

## 1. What are the total number of orders placed?

In [32]:
ords.head(5)

   order_details_id  order_id order_date   order_time  item_id
0                 1         1     1/1/23  11:38:36 AM    109.0
1                 2         2     1/1/23  11:57:40 AM    108.0
2                 3         2     1/1/23  11:57:40 AM    124.0
3                 4         2     1/1/23  11:57:40 AM    117.0
4                 5         2     1/1/23  11:57:40 AM    129.0

In [33]:
ords.order_id.nunique()

5370

In [34]:
# There are 5370 orders placed by the users.

## 2. How many unique menu items are available?

In [35]:
men.head(5)

   item_id      item_name  category  price
0      101      Hamburger  American  12.95
1      102   Cheeseburger  American  13.95
2      103        Hot Dog  American   9.00
3      104  Veggie Burger  American  10.50
4      105   Mac & Cheese  American   7.00

In [82]:
men.item_id.nunique()

32

In [37]:
# 32 unique items are available in the restaurant.

## 3. What is the average price of menu items?

In [38]:
men.head(5)

   item_id      item_name  category  price
0      101      Hamburger  American  12.95
1      102   Cheeseburger  American  13.95
2      103        Hot Dog  American   9.00
3      104  Veggie Burger  American  10.50
4      105   Mac & Cheese  American   7.00

In [39]:
men.price.mean()

np.float64(13.2859375)

In [40]:
# the average of price is approx 13.29

## 4. Which are the top 5 most frequently ordered items?

In [41]:
ords.head(5)

   order_details_id  order_id order_date   order_time  item_id
0                 1         1     1/1/23  11:38:36 AM    109.0
1                 2         2     1/1/23  11:57:40 AM    108.0
2                 3         2     1/1/23  11:57:40 AM    124.0
3                 4         2     1/1/23  11:57:40 AM    117.0
4                 5         2     1/1/23  11:57:40 AM    129.0

In [42]:
men.head(5)

   item_id      item_name  category  price
0      101      Hamburger  American  12.95
1      102   Cheeseburger  American  13.95
2      103        Hot Dog  American   9.00
3      104  Veggie Burger  American  10.50
4      105   Mac & Cheese  American   7.00

In [43]:
 df = pd.merge(men, ords, how='inner', on='item_id')

In [44]:
df

,item_id,item_name,category,price,order_details_id,order_id,order_date,order_time
0,101,Hamburger,American,12.95,11,6,1/1/23,12:29:36 PM
1,101,Hamburger,American,12.95,26,11,1/1/23,1:02:59 PM
2,101,Hamburger,American,12.95,43,17,1/1/23,1:53:00 PM
3,101,Hamburger,American,12.95,63,24,1/1/23,2:23:01 PM
4,101,Hamburger,American,12.95,71,27,1/1/23,3:11:17 PM
...,...,...,...,...,...,...,...,...
12092,132,Eggplant Parmesan,Italian,16.95,12120,5322,3/31/23,1:35:58 PM
12093,132,Eggplant Parmesan,Italian,16.95,12126,5326,3/31/23,1:50:17 PM
12094,132,Eggplant Parmesan,Italian,16.95,12149,5334,3/31/23,3:29:36 PM
12095,132,Eggplant Parmesan,Italian,16.95,12169,5344,3/31/23,5:22:40 PM
12096,132,Eggplant Parmesan,Italian,16.95,12194,5355,3/31/23,6:51:00 PM

In [45]:
df.item_name.value_counts().head(5)

item_name
Hamburger           622
Edamame             620
Korean Beef Bowl    588
Cheeseburger        583
French Fries        571
Name: count, dtype: int64

In [46]:
 # Hamburger, Edamame, Korean Beef Bowl, Cheeseburger, and French Fries are the top most frequently ordered products.

# Intermediate Questions

## 5. What is the total revenue generated from all orders?

In [47]:
ords.head(5)

   order_details_id  order_id order_date   order_time  item_id
0                 1         1     1/1/23  11:38:36 AM    109.0
1                 2         2     1/1/23  11:57:40 AM    108.0
2                 3         2     1/1/23  11:57:40 AM    124.0
3                 4         2     1/1/23  11:57:40 AM    117.0
4                 5         2     1/1/23  11:57:40 AM    129.0

In [48]:
men.head(5)

   item_id      item_name  category  price
0      101      Hamburger  American  12.95
1      102   Cheeseburger  American  13.95
2      103        Hot Dog  American   9.00
3      104  Veggie Burger  American  10.50
4      105   Mac & Cheese  American   7.00

In [49]:
rev = pd.merge(ords, men, how='left', on='item_id')

In [50]:
total_revenue = rev['price'].sum()
total_revenue

np.float64(159217.90000000002)

In [51]:
# total revenue is 159217.90000000002

## 6. Which category generates the highest revenue?

In [52]:
rev.head(5)

,order_details_id,order_id,order_date,order_time,item_id,item_name,category,price
0,1,1,1/1/23,11:38:36 AM,109.0,Korean Beef Bowl,Asian,17.95
1,2,2,1/1/23,11:57:40 AM,108.0,Tofu Pad Thai,Asian,14.50
2,3,2,1/1/23,11:57:40 AM,124.0,Spaghetti,Italian,14.50
3,4,2,1/1/23,11:57:40 AM,117.0,Chicken Burrito,Mexican,12.95
4,5,2,1/1/23,11:57:40 AM,129.0,Mushroom Ravioli,Italian,15.50

In [53]:
rev.groupby(by='category')['price'].sum()

category
American    28237.75
Asian       46720.65
Italian     49462.70
Mexican     34796.80
Name: price, dtype: float64

## 7. What is the average order value (AOV)?

np.float64(159217.90000000002)

In [85]:
odr = rev.groupby(by='order_id')['price'].sum()

In [86]:
odr.mean()

np.float64(29.64951582867784)

In [55]:
# approx 29.64 is the average order value (AOV)

## 8. Which menu items are least popular?

In [56]:
rev.head(5)

,order_details_id,order_id,order_date,order_time,item_id,item_name,category,price
0,1,1,1/1/23,11:38:36 AM,109.0,Korean Beef Bowl,Asian,17.95
1,2,2,1/1/23,11:57:40 AM,108.0,Tofu Pad Thai,Asian,14.50
2,3,2,1/1/23,11:57:40 AM,124.0,Spaghetti,Italian,14.50
3,4,2,1/1/23,11:57:40 AM,117.0,Chicken Burrito,Mexican,12.95
4,5,2,1/1/23,11:57:40 AM,129.0,Mushroom Ravioli,Italian,15.50

In [89]:
least_order = rev.groupby(by='item_name').order_id.count()
least_order.sort_values(ascending=True).head(5)

item_name
Chicken Tacos         123
Potstickers           205
Cheese Lasagna        207
Steak Tacos           214
Cheese Quesadillas    233
Name: order_id, dtype: int64

# Advance Questions

## 9. At what time are the most orders placed?

In [58]:
ords.head(5)

   order_details_id  order_id order_date   order_time  item_id
0                 1         1     1/1/23  11:38:36 AM    109.0
1                 2         2     1/1/23  11:57:40 AM    108.0
2                 3         2     1/1/23  11:57:40 AM    124.0
3                 4         2     1/1/23  11:57:40 AM    117.0
4                 5         2     1/1/23  11:57:40 AM    129.0

In [59]:
ords.dtypes

order_details_id      int64
order_id              int64
order_date           object
order_time           object
item_id             float64
dtype: object

In [60]:
# As we clearly see that the 'order_date' and 'order_time' are of 'object' data types. And we need to change it from object 
# to datetime format.

In [101]:
import warnings
warnings.filterwarnings('ignore')

In [102]:
ords['order_date'] = pd.to_datetime(ords['order_date'], errors='coerce')

In [103]:
ords['order_time'] = pd.to_datetime(ords['order_time'])

In [64]:
ords.dtypes

order_details_id             int64
order_id                     int64
order_date          datetime64[ns]
order_time          datetime64[ns]
item_id                    float64
dtype: object

In [65]:
ords.head(5)

   order_details_id  order_id order_date          order_time  item_id
0                 1         1 2023-01-01 2026-04-14 11:38:36    109.0
1                 2         2 2023-01-01 2026-04-14 11:57:40    108.0
2                 3         2 2023-01-01 2026-04-14 11:57:40    124.0
3                 4         2 2023-01-01 2026-04-14 11:57:40    117.0
4                 5         2 2023-01-01 2026-04-14 11:57:40    129.0

In [66]:
# To find out the time of the most order placed at what time, we need to extract 'hour' from the 'order_time' column.

In [67]:
ords['hour'] = ords['order_time'].dt.hour

In [68]:
# Now count the values by hours

In [69]:
hourly_orders = ords['hour'].value_counts().sort_index()

In [70]:
peak_hour = hourly_orders.idxmax()
max_orders = hourly_orders.max()

In [71]:
print('Peak Hour:', peak_hour)
print('Orders:', max_orders)

Peak Hour: 12
Orders: 1672

## 10. Which items contribute the most to total revenue?|

In [81]:
rev.groupby(by='item_name')['price'].sum().sort_values(ascending=False).head(5)

item_name
Korean Beef Bowl         10554.60
Spaghetti & Meatballs     8436.50
Tofu Pad Thai             8149.00
Cheeseburger              8132.85
Hamburger                 8054.90
Name: price, dtype: float64

In [77]:
# Korean Beef Bowl item contributes the most, about 10554.60 of total revenue

## 11. What is the relationship between item price and order frequency?

In [79]:
rev.head(5)

,order_details_id,order_id,order_date,order_time,item_id,item_name,category,price
0,1,1,1/1/23,11:38:36 AM,109.0,Korean Beef Bowl,Asian,17.95
1,2,2,1/1/23,11:57:40 AM,108.0,Tofu Pad Thai,Asian,14.50
2,3,2,1/1/23,11:57:40 AM,124.0,Spaghetti,Italian,14.50
3,4,2,1/1/23,11:57:40 AM,117.0,Chicken Burrito,Mexican,12.95
4,5,2,1/1/23,11:57:40 AM,129.0,Mushroom Ravioli,Italian,15.50

In [90]:
# frequency order
feq_ord = rev['item_name'].value_counts().rename('order_count')

In [98]:
# price per item 
price = rev.drop_duplicates('item_name').set_index('item_name')['price']

In [99]:
#combine 
analysis = pd.concat([feq_ord, price], axis=1).dropna()

In [100]:
analysis.sort_values('order_count', ascending=False)

                       order_count  price
item_name
Hamburger                    622.0  12.95
Edamame                      620.0   5.00
Korean Beef Bowl             588.0  17.95
Cheeseburger                 583.0  13.95
French Fries                 571.0   7.00
Tofu Pad Thai                562.0  14.50
Steak Torta                  489.0  13.95
Spaghetti & Meatballs        470.0  17.95
Mac & Cheese                 463.0   7.00
Chips & Salsa                461.0   7.00
Orange Chicken               456.0  16.50
Chicken Burrito              455.0  12.95
Eggplant Parmesan            420.0  16.95
Chicken Torta                379.0  11.95
Spaghetti                    367.0  14.50
Chicken Parmesan             364.0  17.95
Pork Ramen                   360.0  17.95
Mushroom Ravioli             359.0  15.50
California Roll              355.0  11.95
Steak Burrito                354.0  14.95
Salmon Roll                  324.0  14.95
Meat Lasagna                 273.0  17.95
Hot Dog                      257.0   9.00
Fettuccine Alfredo           249.0  14.50
Shrimp Scampi                239.0  19.95
Veggie Burger                238.0  10.50
Chips & Guacamole            237.0   9.00
Cheese Quesadillas           233.0  10.50
Steak Tacos                  214.0  13.95
Cheese Lasagna               207.0  15.50
Potstickers                  205.0   9.00
Chicken Tacos                123.0  11.95